service: apartment-search

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"


functions:
  aptsearch:
    handler: lambda.run
    events:
      - http:
          path: /
          method: get
